import type { HandPose } from '@asl/sign-schema';

/** Flat joint rotation map for interpolation (radians, primarily X-axis flexion) */
export type FlatHandPose = Record<string, number>;

export const JOINT_NAMES = [
  'thumbCmc',
  'thumbCmcY',
  'thumbMcp',
  'thumbIp',
  'indexMcp',
  'indexMcpSpread',
  'indexPip',
  'indexDip',
  'middleMcp',
  'middlePip',
  'middleDip',
  'ringMcp',
  'ringMcpSpread',
  'ringPip',
  'ringDip',
  'pinkyMcp',
  'pinkyMcpSpread',
  'pinkyPip',
  'pinkyDip',
  'wristRotX',
  'wristRotY',
  'wristRotZ',
] as const;

export function flatToHandPose(flat: FlatHandPose): HandPose {
  return {
    thumbCmc: { x: flat.thumbCmc ?? 0, y: flat.thumbCmcY ?? 0, z: 0 },
    thumbMcp: { x: flat.thumbMcp ?? 0, y: 0, z: 0 },
    thumbIp: { x: flat.thumbIp ?? 0, y: 0, z: 0 },
    indexMcp: { x: flat.indexMcp ?? 0, y: flat.indexMcpSpread ?? 0, z: 0 },
    indexPip: { x: flat.indexPip ?? 0, y: 0, z: 0 },
    indexDip: { x: flat.indexDip ?? 0, y: 0, z: 0 },
    middleMcp: { x: flat.middleMcp ?? 0, y: 0, z: 0 },
    middlePip: { x: flat.middlePip ?? 0, y: 0, z: 0 },
    middleDip: { x: flat.middleDip ?? 0, y: 0, z: 0 },
    ringMcp: { x: flat.ringMcp ?? 0, y: flat.ringMcpSpread ?? 0, z: 0 },
    ringPip: { x: flat.ringPip ?? 0, y: 0, z: 0 },
    ringDip: { x: flat.ringDip ?? 0, y: 0, z: 0 },
    pinkyMcp: { x: flat.pinkyMcp ?? 0, y: flat.pinkyMcpSpread ?? 0, z: 0 },
    pinkyPip: { x: flat.pinkyPip ?? 0, y: 0, z: 0 },
    pinkyDip: { x: flat.pinkyDip ?? 0, y: 0, z: 0 },
    rotation: [flat.wristRotX ?? 0, flat.wristRotY ?? 0, flat.wristRotZ ?? 0],
  };
}

const CLOSED: FlatHandPose = {
  indexMcp: 1.4,
  indexPip: 1.6,
  indexDip: 1.2,
  middleMcp: 1.4,
  middlePip: 1.6,
  middleDip: 1.2,
  ringMcp: 1.4,
  ringPip: 1.6,
  ringDip: 1.2,
  pinkyMcp: 1.4,
  pinkyPip: 1.6,
  pinkyDip: 1.2,
  thumbMcp: 0.3,
  thumbIp: 0.4,
  thumbCmc: 0.2,
};

const OPEN: FlatHandPose = {
  indexMcp: 0,
  indexPip: 0,
  indexDip: 0,
  middleMcp: 0,
  middlePip: 0,
  middleDip: 0,
  ringMcp: 0,
  ringPip: 0,
  ringDip: 0,
  pinkyMcp: 0,
  pinkyPip: 0,
  pinkyDip: 0,
  thumbMcp: 0,
  thumbIp: 0,
  thumbCmc: 0.4,
  thumbCmcY: -0.5,
};

/** ASL fingerspelling hand poses (right hand, palm facing viewer) */
export const FINGERSPELLING_POSES: Record<string, FlatHandPose> = {
  A: {
    ...CLOSED,
    thumbMcp: 0.1,
    thumbIp: 0.1,
    thumbCmc: -0.3,
    thumbCmcY: 0.8,
  },
  B: {
    ...OPEN,
    thumbMcp: 0.8,
    thumbIp: 0.6,
    thumbCmc: 0.5,
    thumbCmcY: -0.3,
  },
  C: {
    indexMcp: 0.5,
    indexPip: 0.6,
    middleMcp: 0.5,
    middlePip: 0.6,
    ringMcp: 0.5,
    ringPip: 0.6,
    pinkyMcp: 0.5,
    pinkyPip: 0.6,
    thumbMcp: 0.4,
    thumbIp: 0.4,
    thumbCmc: 0.3,
  },
  D: {
    ...CLOSED,
    indexMcp: 0,
    indexPip: 0,
    indexDip: 0,
    thumbMcp: 0.6,
    thumbIp: 0.5,
    thumbCmc: 0.4,
    thumbCmcY: -0.4,
  },
  E: {
    indexMcp: 1.0,
    indexPip: 1.3,
    indexDip: 0.8,
    middleMcp: 1.0,
    middlePip: 1.3,
    middleDip: 0.8,
    ringMcp: 1.0,
    ringPip: 1.3,
    ringDip: 0.8,
    pinkyMcp: 1.0,
    pinkyPip: 1.3,
    pinkyDip: 0.8,
    thumbMcp: 0.9,
    thumbIp: 0.7,
    thumbCmc: 0.3,
  },
  F: {
    indexMcp: 0.8,
    indexPip: 1.0,
    middleMcp: 0.8,
    middlePip: 1.0,
    ringMcp: 0.8,
    ringPip: 1.0,
    pinkyMcp: 0.8,
    pinkyPip: 1.0,
    thumbMcp: 0.2,
    thumbIp: 0.2,
    thumbCmc: 0.6,
    thumbCmcY: -0.6,
  },
  G: {
    indexMcp: 0,
    indexPip: 0,
    indexDip: 0,
    middleMcp: 1.4,
    middlePip: 1.6,
    middleDip: 1.2,
    ringMcp: 1.4,
    ringPip: 1.6,
    ringDip: 1.2,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    pinkyDip: 1.2,
    thumbMcp: 0.3,
    thumbIp: 0.4,
    thumbCmc: 0.5,
    thumbCmcY: -0.8,
    wristRotZ: -0.4,
  },
  H: {
    indexMcp: 0,
    indexPip: 0,
    indexDip: 0,
    middleMcp: 0,
    middlePip: 0,
    middleDip: 0,
    ringMcp: 1.4,
    ringPip: 1.6,
    ringDip: 1.2,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    pinkyDip: 1.2,
    thumbMcp: 0.3,
    thumbIp: 0.4,
    thumbCmc: 0.3,
    wristRotZ: -0.4,
  },
  I: {
    ...CLOSED,
    pinkyMcp: 0,
    pinkyPip: 0,
    pinkyDip: 0,
  },
  J: {
    ...CLOSED,
    pinkyMcp: 0,
    pinkyPip: 0,
    pinkyDip: 0,
    wristRotY: 0.6,
  },
  K: {
    indexMcp: 0,
    indexPip: 0,
    indexDip: 0,
    middleMcp: 0,
    middlePip: 0,
    middleDip: 0,
    ringMcp: 1.4,
    ringPip: 1.6,
    ringDip: 1.2,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    pinkyDip: 1.2,
    thumbMcp: 0.4,
    thumbIp: 0.3,
    thumbCmc: 0.5,
    thumbCmcY: -0.3,
    indexMcpSpread: 0.15,
  },
  L: {
    indexMcp: 0,
    indexPip: 0,
    indexDip: 0,
    middleMcp: 1.4,
    middlePip: 1.6,
    middleDip: 1.2,
    ringMcp: 1.4,
    ringPip: 1.6,
    ringDip: 1.2,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    pinkyDip: 1.2,
    thumbMcp: 0,
    thumbIp: 0,
    thumbCmc: 0.8,
    thumbCmcY: -1.0,
  },
  M: {
    ...CLOSED,
    thumbMcp: 0.1,
    thumbIp: 0.1,
    thumbCmc: 0.6,
    thumbCmcY: 0.5,
    indexMcpSpread: -0.1,
    middleMcpSpread: -0.1,
    ringMcpSpread: -0.1,
  },
  N: {
    ...CLOSED,
    thumbMcp: 0.1,
    thumbIp: 0.1,
    thumbCmc: 0.5,
    thumbCmcY: 0.4,
    indexMcpSpread: -0.05,
  },
  O: {
    indexMcp: 0.9,
    indexPip: 1.0,
    middleMcp: 0.9,
    middlePip: 1.0,
    ringMcp: 0.9,
    ringPip: 1.0,
    pinkyMcp: 0.9,
    pinkyPip: 1.0,
    thumbMcp: 0.7,
    thumbIp: 0.7,
    thumbCmc: 0.5,
    thumbCmcY: -0.4,
  },
  P: {
    indexMcp: 0,
    indexPip: 0,
    middleMcp: 0,
    middlePip: 0,
    ringMcp: 1.4,
    ringPip: 1.6,
    ringDip: 1.2,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    pinkyDip: 1.2,
    thumbMcp: 0.4,
    thumbIp: 0.3,
    thumbCmc: 0.5,
    wristRotX: -0.8,
  },
  Q: {
    indexMcp: 0,
    indexPip: 0,
    middleMcp: 1.4,
    middlePip: 1.6,
    middleDip: 1.2,
    ringMcp: 1.4,
    ringPip: 1.6,
    ringDip: 1.2,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    pinkyDip: 1.2,
    thumbMcp: 0.3,
    thumbIp: 0.4,
    thumbCmc: 0.5,
    wristRotX: -0.8,
    wristRotZ: -0.3,
  },
  R: {
    indexMcp: 0,
    indexPip: 0,
    indexDip: 0,
    middleMcp: 0,
    middlePip: 0,
    middleDip: 0,
    ringMcp: 1.4,
    ringPip: 1.6,
    ringDip: 1.2,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    pinkyDip: 1.2,
    thumbMcp: 0.3,
    thumbIp: 0.4,
    thumbCmc: 0.3,
    indexMcpSpread: 0.25,
  },
  S: { ...CLOSED },
  T: {
    ...CLOSED,
    thumbMcp: 0.2,
    thumbIp: 0.2,
    thumbCmc: 0.3,
    thumbCmcY: 0.3,
    indexMcpSpread: 0.1,
  },
  U: {
    indexMcp: 0,
    indexPip: 0,
    indexDip: 0,
    middleMcp: 0,
    middlePip: 0,
    middleDip: 0,
    ringMcp: 1.4,
    ringPip: 1.6,
    ringDip: 1.2,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    pinkyDip: 1.2,
    thumbMcp: 0.8,
    thumbIp: 0.6,
    thumbCmc: 0.4,
  },
  V: {
    indexMcp: 0,
    indexPip: 0,
    indexDip: 0,
    middleMcp: 0,
    middlePip: 0,
    middleDip: 0,
    ringMcp: 1.4,
    ringPip: 1.6,
    ringDip: 1.2,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    pinkyDip: 1.2,
    thumbMcp: 0.8,
    thumbIp: 0.6,
    thumbCmc: 0.4,
    indexMcpSpread: 0.2,
  },
  W: {
    indexMcp: 0,
    indexPip: 0,
    middleMcp: 0,
    middlePip: 0,
    ringMcp: 0,
    ringPip: 0,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    pinkyDip: 1.2,
    thumbMcp: 0,
    thumbIp: 0,
    thumbCmc: 0.6,
    indexMcpSpread: 0.15,
    ringMcpSpread: 0.15,
  },
  X: {
    ...CLOSED,
    indexMcp: 0.8,
    indexPip: 1.2,
    indexDip: 0.6,
  },
  Y: {
    ...CLOSED,
    pinkyMcp: 0,
    pinkyPip: 0,
    pinkyDip: 0,
    thumbMcp: 0,
    thumbIp: 0,
    thumbCmc: 0.8,
    thumbCmcY: -1.0,
  },
  '0': {
    indexMcp: 0.9,
    indexPip: 1.0,
    middleMcp: 0.9,
    middlePip: 1.0,
    ringMcp: 0.9,
    ringPip: 1.0,
    pinkyMcp: 0.9,
    pinkyPip: 1.0,
    thumbMcp: 0.7,
    thumbIp: 0.7,
    thumbCmc: 0.5,
    thumbCmcY: -0.4,
  },
  '1': {
    indexMcp: 0,
    indexPip: 0,
    indexDip: 0,
    middleMcp: 1.4,
    middlePip: 1.6,
    middleDip: 1.2,
    ringMcp: 1.4,
    ringPip: 1.6,
    ringDip: 1.2,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    pinkyDip: 1.2,
    thumbMcp: 0.8,
    thumbIp: 0.6,
    thumbCmc: 0.4,
  },
  '2': {
    indexMcp: 0,
    indexPip: 0,
    middleMcp: 0,
    middlePip: 0,
    ringMcp: 1.4,
    ringPip: 1.6,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    thumbMcp: 0.8,
    thumbIp: 0.6,
    thumbCmc: 0.4,
    indexMcpSpread: 0.15,
  },
  '3': {
    indexMcp: 0,
    indexPip: 0,
    middleMcp: 0,
    middlePip: 0,
    ringMcp: 0,
    ringPip: 0,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    thumbMcp: 0.8,
    thumbIp: 0.6,
    thumbCmc: 0.4,
    indexMcpSpread: 0.15,
    ringMcpSpread: 0.15,
  },
  '4': {
    indexMcp: 0,
    indexPip: 0,
    middleMcp: 0,
    middlePip: 0,
    ringMcp: 0,
    ringPip: 0,
    pinkyMcp: 0,
    pinkyPip: 0,
    thumbMcp: 0.8,
    thumbIp: 0.6,
    thumbCmc: 0.4,
  },
  '5': { ...OPEN },
  '6': {
    ...OPEN,
    thumbMcp: 0.2,
    thumbIp: 0.2,
    thumbCmc: 0.6,
    thumbCmcY: -0.8,
    wristRotY: 0.3,
  },
  '7': {
    indexMcp: 0,
    indexPip: 0,
    middleMcp: 1.4,
    middlePip: 1.6,
    ringMcp: 1.4,
    ringPip: 1.6,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    thumbMcp: 0.8,
    thumbIp: 0.6,
    thumbCmc: 0.4,
    wristRotY: 0.3,
  },
  '8': {
    indexMcp: 0,
    indexPip: 0,
    middleMcp: 0,
    middlePip: 0,
    ringMcp: 1.4,
    ringPip: 1.6,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    thumbMcp: 0.8,
    thumbIp: 0.6,
    thumbCmc: 0.4,
    indexMcpSpread: 0.15,
    wristRotY: 0.3,
  },
  '9': {
    indexMcp: 0.8,
    indexPip: 1.0,
    middleMcp: 1.4,
    middlePip: 1.6,
    ringMcp: 1.4,
    ringPip: 1.6,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    thumbMcp: 0.8,
    thumbIp: 0.6,
    thumbCmc: 0.4,
    wristRotY: 0.3,
  },
  NEUTRAL: {
    ...OPEN,
    wristRotX: 0.2,
  },
};

/** Common ASL sign poses */
export const SIGN_POSES: Record<string, FlatHandPose> = {
  ...FINGERSPELLING_POSES,
  HELLO: {
    ...OPEN,
    wristRotY: 0.3,
    wristRotX: -0.2,
  },
  THANK_YOU: {
    ...OPEN,
    wristRotX: -0.3,
  },
  PLEASE: {
    ...OPEN,
    wristRotX: 0.4,
    indexMcp: 0.2,
    middleMcp: 0.2,
    ringMcp: 0.2,
    pinkyMcp: 0.2,
  },
  YES: {
    ...FINGERSPELLING_POSES.S,
    wristRotY: 0.5,
  },
  NO: {
    indexMcp: 0,
    indexPip: 0,
    middleMcp: 1.4,
    middlePip: 1.6,
    ringMcp: 1.4,
    ringPip: 1.6,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    thumbMcp: 0.3,
    thumbIp: 0.4,
    thumbCmc: 0.3,
    indexMcpSpread: 0.3,
    wristRotZ: 0.3,
  },
  HELP: {
    ...FINGERSPELLING_POSES.A,
    thumbMcp: 0.5,
    thumbIp: 0.4,
    thumbCmc: 0.6,
    thumbCmcY: -0.5,
    wristRotY: -0.2,
  },
  NAME: {
    indexMcp: 0,
    indexPip: 0,
    middleMcp: 1.4,
    middlePip: 1.6,
    ringMcp: 1.4,
    ringPip: 1.6,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    thumbMcp: 0.3,
    thumbIp: 0.4,
    thumbCmc: 0.3,
    indexMcpSpread: 0.2,
    wristRotX: 0.2,
  },
  WHAT: {
    indexMcp: 0,
    indexPip: 0,
    middleMcp: 1.4,
    middlePip: 1.6,
    ringMcp: 1.4,
    ringPip: 1.6,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    thumbMcp: 0.3,
    thumbIp: 0.4,
    thumbCmc: 0.3,
    wristRotY: 0.4,
  },
  WHO: {
    indexMcp: 0,
    indexPip: 0,
    middleMcp: 1.4,
    middlePip: 1.6,
    ringMcp: 1.4,
    ringPip: 1.6,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    thumbMcp: 0.3,
    thumbIp: 0.4,
    thumbCmc: 0.3,
    wristRotY: 0.2,
  },
  WHERE: {
    indexMcp: 0,
    indexPip: 0,
    middleMcp: 1.4,
    middlePip: 1.6,
    ringMcp: 1.4,
    ringPip: 1.6,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    thumbMcp: 0.3,
    thumbIp: 0.4,
    thumbCmc: 0.3,
    wristRotX: -0.3,
  },
  RED: {
    indexMcp: 0.3,
    indexPip: 0.5,
    middleMcp: 1.4,
    middlePip: 1.6,
    ringMcp: 1.4,
    ringPip: 1.6,
    pinkyMcp: 1.4,
    pinkyPip: 1.6,
    thumbMcp: 0.3,
    thumbIp: 0.4,
    thumbCmc: 0.3,
    wristRotX: 0.3,
  },
  BLUE: {
    ...FINGERSPELLING_POSES.B,
    wristRotX: 0.2,
    wristRotY: 0.2,
  },
  GREEN: {
    ...FINGERSPELLING_POSES.G,
    wristRotX: 0.2,
  },
  MOTHER: {
    ...FINGERSPELLING_POSES['5'],
    thumbMcp: 0.2,
    thumbIp: 0.2,
    wristRotX: 0.3,
  },
  FATHER: {
    ...FINGERSPELLING_POSES['5'],
    thumbMcp: 0.2,
    thumbIp: 0.2,
    wristRotX: -0.3,
  },
};

export function getDefaultPose(): FlatHandPose {
  return { ...FINGERSPELLING_POSES.NEUTRAL };
}
